# Generated by Django 4.1.5 on 2023-01-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="posts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("desciption", models.TextField()),
                ("create_at", models.DateTimeField()),
                ("update_at", models.DateTimeField()),
            ],
        ),
    ]
