# Generated by Django 4.1.5 on 2023-01-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
